#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# DMagyBOT — Universal Installer
# Supports interactive mode (no args) and automation (--token / --user-id)
# ─────────────────────────────────────────────────────────────────────────────

BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
CYAN="\033[0;36m"
RESET="\033[0m"

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVICE_NAME="dmagybot"
VENV_DIR="${PROJECT_DIR}/.venv"
ENV_FILE="${PROJECT_DIR}/.env"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

# ─────────────────── Helpers ───────────────────────────────────────────────
info()    { echo -e "${GREEN}✅ $1${RESET}"; }
warn()    { echo -e "${YELLOW}⚠️  $1${RESET}"; }
error()   { echo -e "${RED}❌ $1${RESET}"; exit 1; }
header()  { echo -e "\n${CYAN}${BOLD}$1${RESET}\n"; }

# ─────────────────── Parse CLI Arguments ───────────────────────────────────
BOT_TOKEN=""
USER_IDS=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --token=*)    BOT_TOKEN="${1#*=}"; shift ;;
        --token)      BOT_TOKEN="$2"; shift 2 ;;
        --user-id=*)  USER_IDS="${1#*=}"; shift ;;
        --user-id)    USER_IDS="$2"; shift 2 ;;
        --help|-h)
            echo "Usage: ./setup.sh [--token=BOT_TOKEN] [--user-id=TELEGRAM_USER_ID]"
            echo ""
            echo "  --token     Telegram Bot Token from @BotFather"
            echo "  --user-id   Comma-separated list of allowed Telegram user IDs"
            echo ""
            echo "If arguments are omitted, the installer will ask interactively."
            exit 0
            ;;
        *) warn "Unknown argument: $1"; shift ;;
    esac
done

# ─────────────────── Banner ────────────────────────────────────────────────
clear
echo -e "${BOLD}${CYAN}"
cat << 'BANNER'

    ██████╗ ███╗   ███╗ █████╗  ██████╗██╗   ██╗██████╗  ██████╗ ████████╗
    ██╔══██╗████╗ ████║██╔══██╗██╔════╝╚██╗ ██╔╝██╔══██╗██╔═══██╗╚══██╔══╝
    ██║  ██║██╔████╔██║███████║██║  ███╗╚████╔╝ ██████╔╝██║   ██║   ██║
    ██║  ██║██║╚██╔╝██║██╔══██║██║   ██║ ╚██╔╝  ██╔══██╗██║   ██║   ██║
    ██████╔╝██║ ╚═╝ ██║██║  ██║╚██████╔╝  ██║   ██████╔╝╚██████╔╝   ██║
    ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝   ╚═╝   ╚═════╝  ╚═════╝    ╚═╝

BANNER
echo -e "${RESET}"
echo -e "${BOLD}    Telegram Bridge for Google Antigravity CLI${RESET}"
echo -e "    Installer v1.0"
echo ""

# ─────────────────── Step 1: Check Prerequisites ──────────────────────────
header "Шаг 1 из 5: Проверка зависимостей"

# Check Python 3.10+
if ! command -v python3 &>/dev/null; then
    error "Python 3 не найден. Установите Python 3.10+ и повторите."
fi
PY_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
info "Python ${PY_VERSION} найден"

# Check agy CLI
AGY_PATH=""
if command -v agy &>/dev/null; then
    AGY_PATH="$(command -v agy)"
elif [[ -f "$HOME/.local/bin/agy" ]]; then
    AGY_PATH="$HOME/.local/bin/agy"
fi

if [[ -z "$AGY_PATH" ]]; then
    error "Antigravity CLI (agy) не найден!\n\n   Сначала установите agy и авторизуйтесь:\n   curl -sS https://dl.google.com/agy/install.sh | bash\n   agy auth login"
fi
info "Antigravity CLI найден: ${AGY_PATH}"

# Check agy auth
TOKEN_FILE="$HOME/.gemini/antigravity-cli/antigravity-oauth-token"
if [[ ! -f "$TOKEN_FILE" ]]; then
    error "Вы не авторизованы в Antigravity CLI!\n\n   Выполните: agy auth login"
fi
info "Авторизация Antigravity CLI подтверждена"

# ─────────────────── Step 2: Bot Token & User ID ──────────────────────────
header "Шаг 2 из 5: Настройка Telegram"

if [[ -z "$BOT_TOKEN" ]]; then
    echo -e "${BOLD}Введите токен Telegram бота${RESET}"
    echo -e "  (Получить у @BotFather → /newbot)"
    echo ""
    read -rp "  🔑 Bot Token: " BOT_TOKEN
    echo ""
fi

if [[ -z "$BOT_TOKEN" ]]; then
    error "Токен бота не может быть пустым!"
fi

# Validate token format (rough check: contains ':')
if [[ "$BOT_TOKEN" != *":"* ]]; then
    warn "Токен не содержит ':' — проверьте правильность формата."
fi

info "Токен бота принят"

if [[ -z "$USER_IDS" ]]; then
    echo -e "${BOLD}Введите ваш Telegram User ID${RESET}"
    echo -e "  (Узнать у @userinfobot или @getmyid_bot)"
    echo -e "  (Можно указать несколько через запятую: 123,456)"
    echo ""
    read -rp "  👤 User ID: " USER_IDS
    echo ""
fi

if [[ -z "$USER_IDS" ]]; then
    error "User ID не может быть пустым!"
fi

info "User ID принят: ${USER_IDS}"

# ─────────────────── Step 3: Create .env ──────────────────────────────────
header "Шаг 3 из 5: Создание конфигурации"

cat > "$ENV_FILE" << EOF
# DMagyBOT Configuration (auto-generated by setup.sh)
TELEGRAM_BOT_TOKEN="${BOT_TOKEN}"
ALLOWED_USER_IDS="${USER_IDS}"
LOG_LEVEL="INFO"
AGY_BINARY_PATH="${AGY_PATH}"
EOF
chmod 600 "$ENV_FILE"
info "Файл .env создан и защищен (chmod 600)"

# ─────────────────── Step 4: Python Virtual Environment ───────────────────
header "Шаг 4 из 5: Установка зависимостей"

if [[ ! -d "$VENV_DIR" ]]; then
    python3 -m venv "$VENV_DIR"
    info "Виртуальное окружение создано: ${VENV_DIR}"
else
    info "Виртуальное окружение уже существует"
fi

"${VENV_DIR}/bin/pip" install --quiet --upgrade pip
"${VENV_DIR}/bin/pip" install --quiet aiogram pexpect pyte python-dotenv
info "Все зависимости установлены"

# ─────────────────── Step 5: Systemd Service ──────────────────────────────
header "Шаг 5 из 5: Настройка автозапуска (systemd)"

CURRENT_USER="$(whoami)"

cat > "$SERVICE_FILE" << EOF
[Unit]
Description=DMagyBOT - Telegram Bridge for Antigravity AGY
After=network.target

[Service]
Type=simple
User=${CURRENT_USER}
WorkingDirectory=${PROJECT_DIR}
Environment="PYTHONPATH=${PROJECT_DIR}"
ExecStart=${VENV_DIR}/bin/python src/main.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

info "Systemd-сервис создан: ${SERVICE_FILE}"

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}" --quiet
systemctl restart "${SERVICE_NAME}"

info "Сервис ${SERVICE_NAME} запущен и добавлен в автозапуск"

# ─────────────────── Done! ────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════════════${RESET}"
echo -e "${GREEN}${BOLD}  🚀 DMagyBOT успешно установлен и запущен!${RESET}"
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════════════${RESET}"
echo ""
echo -e "  ${BOLD}Что дальше:${RESET}"
echo -e "  1. Откройте Telegram и найдите вашего бота"
echo -e "  2. Отправьте ${BOLD}/start${RESET} для начала работы"
echo -e "  3. Отправьте ${BOLD}/menu${RESET} для панели управления"
echo ""
echo -e "  ${BOLD}Полезные команды:${RESET}"
echo -e "  • Статус бота:   ${CYAN}systemctl status ${SERVICE_NAME}${RESET}"
echo -e "  • Логи бота:     ${CYAN}journalctl -u ${SERVICE_NAME} -f${RESET}"
echo -e "  • Перезапуск:    ${CYAN}systemctl restart ${SERVICE_NAME}${RESET}"
echo -e "  • Остановка:     ${CYAN}systemctl stop ${SERVICE_NAME}${RESET}"
echo ""
echo -e "  ${BOLD}Документация:${RESET} ${CYAN}cat README.md${RESET}"
echo ""
