import os
import subprocess
import shutil
import uuid
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

class Sandbox:
    """Manages an isolated ephemeral environment (Git Worktree)."""
    
    def __init__(self, repo_path: str, task_id: str):
        self.repo_path = Path(repo_path).resolve()
        self.task_id = task_id
        self.branch_name = f"auto-repair-{self.task_id}"
        # Store worktrees outside the main repo to prevent agents from messing with the main .git
        self.worktree_path = Path(f"/tmp/ag_sandbox_{self.task_id}")
        self.is_active = False

    def create(self) -> bool:
        """Create an isolated git worktree."""
        try:
            if self.worktree_path.exists():
                subprocess.run(["git", "worktree", "remove", "-f", str(self.worktree_path)], cwd=self.repo_path)
                shutil.rmtree(self.worktree_path, ignore_errors=True)
            
            # Clean up branch if exists
            subprocess.run(["git", "branch", "-D", self.branch_name], cwd=self.repo_path, check=False, capture_output=True)
            
            # Add worktree directly (it creates the branch)
            res = subprocess.run(
                ["git", "worktree", "add", "-b", self.branch_name, str(self.worktree_path), "main"],
                cwd=self.repo_path, capture_output=True, text=True
            )
            if res.returncode != 0:
                logger.error(f"Git worktree failed: {res.stderr}")
                return False
                
            self.is_active = True
            logger.info(f"Sandbox created at {self.worktree_path}")
            return True
        except Exception as e:
            logger.error(f"Failed to create sandbox: {e}")
            return False

    def apply_patch(self, patch_content: str) -> bool:
        """Apply a patch generated by the agent."""
        patch_file = self.worktree_path / "agent.patch"
        patch_file.write_text(patch_content)
        
        res = subprocess.run(["git", "apply", "agent.patch"], cwd=self.worktree_path)
        return res.returncode == 0

    def collect_diff(self) -> str:
        """Extract the agent's changes as a patch."""
        res = subprocess.run(["git", "diff"], cwd=self.worktree_path, capture_output=True, text=True)
        return res.stdout

    def destroy(self):
        """Clean up the worktree and branch."""
        try:
            if self.worktree_path.exists():
                subprocess.run(["git", "worktree", "remove", "-f", str(self.worktree_path)], cwd=self.repo_path)
                shutil.rmtree(self.worktree_path, ignore_errors=True)
            
            subprocess.run(["git", "branch", "-D", self.branch_name], cwd=self.repo_path, check=False)
            self.is_active = False
            logger.info(f"Sandbox {self.task_id} destroyed.")
        except Exception as e:
            logger.error(f"Failed to destroy sandbox: {e}")

    def __enter__(self):
        self.create()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.destroy()
